(set! list (lambda x x))
(set! define (syntax (form . values)
               (if (symbolp form)
                   (list 'set! form (car values))
                   (list 'set! (car form) (cons 'lambda (cons (cdr form) values))))))
(define not null)
(define and (syntax l
              (if (null l)
                  t
                  (if (null (cdr l))
                      (car l)
                      (list 'if (car l) (cons 'and (cdr l)) nil)))))
(define (bindings->formals bindings)
  (if (null bindings)
      nil
      (cons (car (car bindings)) (bindings->formals (cdr bindings)))))
(define (bindings->values bindings)
  (if (null bindings)
      nil
      (cons (car (cdr (car bindings))) (bindings->values (cdr bindings)))))
(define let (syntax (bindings . body)
              (cons (cons 'lambda (cons (bindings->formals bindings) body)) 
                    (bindings->values bindings))))
(define progn (syntax l
                (if (null l)
                    nil
                    (if (null (cdr l))
                        (car l)
                        (let ((s (gensym)))
                          (list 'let (list (list s (car l)))
                            (cons 'progn (cdr l))))))))
(define or (syntax l
             (if (null l)
                 nil
                 (if (null (cdr l))
                     (car l)
                     (let ((s (gensym)))
                       (list 'let (list (list s (car l)))
                         (list 'if s s (cons 'or (cdr l)))))))))
(define let* (syntax (bindings . body)
               (if (null bindings)
                   (cons 'let (cons nil body))
                   (list 'let 
                         (list (car bindings)) 
                         (cons 'let* (cons (cdr bindings) body))))))
; `(let (,(car bindings)) (let* ,(cdr bindings) ,@))
(define (println val)
  (display val)
  (newline))
(define (reverse l)
  (define (reverse-iter l acc)
    (if (null l)
        acc
        (reverse-iter (cdr l) (cons (car l) acc))))
  (reverse-iter l nil))
(define (append-2 a b)
  (define (append-2-rev a b)
    (if (null a)
        b
        (append-2 (cdr a) (cons (car a) b))))
  (append-2-rev (reverse a) b))
(define (bindings->unbounds bindings)
  (if (null bindings)
      nil
      (cons (list (car (car bindings)) '(unbound))
            (bindings->unbounds (cdr bindings)))))
(define (bindings->set! bindings)
  (if (null bindings)
      nil
      (cons (list 'set! (car (car bindings)) (car (cdr (car bindings))))
            (bindings->set! (cdr bindings)))))
(define letrec (syntax (bindings . body)
                 (append-2 '(let)
                           (cons (bindings->unbounds bindings)
                                 (append-2 (bindings->set! bindings)
                                           body)))))
